### ISSUE TITLE
Checker and Service Container not communicating 

### ISSUE THREAD

**Issue by Ashiven** [enowars/enowars-service-example#16]
There seems to be an issue at least for me and some others that the checker and service containers are on different networks and therefore unable to reach each other. 

What worked for me was following these steps:

1) List the networks belonging to a container to figure out the containers respective networks:
    "docker inspect -f '{{range $key, $value := .NetworkSettings.Networks}}{{$key}} {{end}}' [containerId]"
2) Add the service's network to the networks of the checker container: 
    "docker network connect [serviceNetworkName] [checkerContainerId]" 
3) Repeat after rebuilding the checker container with docker compose

(Optional) I could then run the tests with enochecker_test as follows:
    "enochecker_test -a localhost -p [checkerPort] -A [serviceDefaultGateway]"

As already mentioned by Matthis the default gateway for the service container can be found out like so:
 "docker network inspect [serviceNetworkName]"
and can be found under IPAM.Config - Gateway

Source: https://maximorlov.com/4-reasons-why-your-docker-containers-cant-talk-to-each-other/

**Comment by MMunier** [comment]
Container from different networks aren't able to communicate, as you've correctly assessed.
However in the real setup, services and checker run on different hosts and this approach can not be done. 

The services and the checker have their ports exposed, so they are available on its interfaces.
Look into the CI-workflow, if sets 3 environment-Variables corresponding to your arguments:

- ENOCHECKER_TEST_CHECKER_ADDRESS
- ENOCHECKER_TEST_CHECKER_PORT
- ENOCHECKER_TEST_SERVICE_ADDRESS

For local testing a standard workflow would be:
```bash
export ENOCHECKER_TEST_CHECKER_ADDRESS=localhost
export ENOCHECKER_TEST_CHECKER_ADDRESS=<your checkers port>
export ENOCHECKER_TEST_SERVICE_ADDRESS=<your Hosts IP>
enochecker_test
```

Which is basically what the workflow does.
https://github.com/enowars/enowars-service-example/blob/main/.github/workflows/enochecker_test.yml
